// <auto-generated />
namespace IkubInternship.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PermissionChange1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PermissionChange1));
        
        string IMigrationMetadata.Id
        {
            get { return "202011222151303_PermissionChange1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
